name: flutter_liquid_glass_plus
description: A beautiful Flutter package for creating stunning liquid glass morphism UI effects. Transform your Flutter apps with elegant, modern glassmorphism designs.
version: 0.0.4
homepage: https://github.com/nugaysamil/flutter_liquid_glass
repository: https://github.com/nugaysamil/flutter_liquid_glass
issue_tracker: https://github.com/nugaysamil/flutter_liquid_glass/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  liquid_glass_renderer: ^0.2.0-dev.4
  motor: ^1.1.0
  
  

dev_dependencies:
  alchemist: ^0.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
